In [79]:
import matplotlib.pyplot as plt
import cv2 as cv
import numpy as np

In [80]:
card = '../../image4labs/dec_cards.jpg'

img = cv.imread(card, cv.IMREAD_GRAYSCALE)
assert img is not None, "file could not be read, check with os.path.exists()"

ret, thresh = cv.threshold(img, 127, 255, 0)
contours, hierarchy = cv.findContours(thresh, 1, 2)

In [91]:
cnt = contours[0]
print(cnt)

[[[396 520]]

 [[395 521]]

 [[393 521]]

 [[392 522]]

 [[392 524]]

 [[391 525]]

 [[391 563]]

 [[392 564]]

 [[392 565]]

 [[394 567]]

 [[400 567]]

 [[402 565]]

 [[402 563]]

 [[403 562]]

 [[403 525]]

 [[402 524]]

 [[402 523]]

 [[401 522]]

 [[401 521]]

 [[399 521]]

 [[398 520]]]


Соотношение сторон
Это отношение ширины к высоте ограничивающего прямоугольника объекта.


In [82]:
x, y, w, h = cv.boundingRect(cnt)
aspect_ratio = float(w)/h
aspect_ratio

0.2708333333333333

Протяженность
Протяженность — это отношение площади контура к площади ограничивающего прямоугольника.


In [83]:
area = cv.contourArea(cnt)
x, y, w, h = cv.boundingRect(cnt)
rect_area = w*h
extent = float(area)/rect_area
extent

0.8557692307692307

Прочность
Прочность — это отношение площади контура к площади выпуклой части корпуса.


In [84]:
hull = cv.convexHull(cnt)
hull_area = cv.contourArea(hull)
solidity = float(area)/hull_area if hull_area != 0 else 'inf'
print("solidity", solidity)

solidity 0.989805375347544


Эквивалентный диаметр
Эквивалентный диаметр — диаметр круга, площадь которого равна площади контура.


In [ ]:
equi_diameter = np.sqrt(4*area/np.pi)
print("equi_diameter", equi_diameter)

equi_diameter 26.075082298788182


Ориентация
Ориентация — это угол, под которым направлен объект. Следующий метод также дает длины Большой и Малой осей.


In [86]:
(x, y), (MA, ma), angle = cv.fitEllipse(cnt)
print("fit elipse", x, y, MA, ma, angle)

fit elipse 396.8733825683594 543.8215942382812 19.22096824645996 48.24970245361328 0.12903480231761932


Маска и пиксельные точки
В некоторых случаях нам могут понадобиться все точки, которые составляют этот объект. Это можно сделать следующим образом:


In [ ]:
mask = np.zeros(img.shape, np.uint8)
cv.drawContours(mask, [cnt], 0, 255, -1)
pixelpoints = np.transpose(np.nonzero(mask))
pixelpoints = cv.findNonZero(mask)
print('pixelpoints', pixelpoints)

pixelpoints [[[396 520]]

 [[397 520]]

 [[398 520]]

 ...

 [[398 567]]

 [[399 567]]

 [[400 567]]]


Максимальное значение, минимальное значение и их местоположение
Эти параметры мы можем найти с помощью изображения-маски.


In [ ]:
min_val, max_val, min_loc, max_loc = cv.minMaxLoc(img, mask=mask)
print("min max loc", min_val, max_val, min_loc, max_loc)

min max loc 128.0 255.0 (403, 560) (394, 522)


Средний цвет или средняя интенсивность
Здесь мы можем найти средний цвет объекта. Или это может быть средняя интенсивность объекта в режиме оттенков серого. Для этого мы снова используем ту же маску.


In [ ]:
mean_val = cv.mean(img, mask=mask)
print("mean_val", mean_val)

mean_val (235.67857142857142, 0.0, 0.0, 0.0)


Крайние точки
Крайние точки — это самая верхняя, самая нижняя, самая правая и самая левая точки объекта.


In [ ]:
leftmost = tuple(cnt[cnt[:, :, 0].argmin()][0])
rightmost = tuple(cnt[cnt[:, :, 0].argmax()][0])
topmost = tuple(cnt[cnt[:, :, 1].argmin()][0])
bottommost = tuple(cnt[cnt[:, :, 1].argmax()][0])
print("points", leftmost, rightmost, topmost, bottommost)

points (np.int32(391), np.int32(525)) (np.int32(403), np.int32(562)) (np.int32(396), np.int32(520)) (np.int32(394), np.int32(567))
